/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darkfllame_jsdl_NativeBindings */

#ifndef _Included_com_darkfllame_jsdl_NativeBindings
#define _Included_com_darkfllame_jsdl_NativeBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_Quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1Quit
  (JNIEnv *, jclass);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_InitSubSystem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1InitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_QuitSubSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1QuitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_WasInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1WasInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetError
  (JNIEnv *, jclass);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetError
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_PollEvent
 * Signature: (Lcom/darkfllame/jsdl/Event;)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1PollEvent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_CreateWindow
 * Signature: (Ljava/lang/String;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1CreateWindow
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_DestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1DestroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetWindowTitle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetWindowTitle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetWindowTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetWindowSize
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetWindowSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetWindowSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetWindowPosition
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetWindowPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetWindowPosition
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetWindowPosition
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetWindowResizable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetWindowResizable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetRenderer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderGetWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderGetWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_CreateRenderer
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1CreateRenderer
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_DestroyRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1DestroyRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetRenderTarget
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetRenderTarget
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetRenderTarget
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetRenderTarget
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_SetRenderDrawColor
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1SetRenderDrawColor
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_GetRenderDrawColor
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1GetRenderDrawColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderClear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderPresent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderPresent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderDrawRect
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderDrawRect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderDrawRectF
 * Signature: (JFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderDrawRectF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderFillRect
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderFillRect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_darkfllame_jsdl_NativeBindings
 * Method:    SDL_RenderFillRectF
 * Signature: (JFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_darkfllame_jsdl_NativeBindings_SDL_1RenderFillRectF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
